import React from "react";
import { Routes, Route, Link } from "react-router-dom";
import Login from "./pages/Login";
import SelectRole from "./pages/SelectRole";
import Register from "./pages/Register";

import Country from "./pages/master/Country";
import Destination from "./pages/master/Destination";
import Hotels from "./pages/master/Hotels";
import PrivateRoute from "./components/PrivateRoute";
import AgentDashboard from "./pages/AgentDashboard";
import AdminDashboard from "./pages/AdminDashboard";
import StaffDashboard from "./pages/StaffDashboard";
import Test from "./pages/Test";
import LandingPage from "./pages/LandingPage";
import { Toaster } from "react-hot-toast";
import Designations from "./pages/master/Designation";
import HotelSearch from "./pages/HotelSearch";
import RoomList from "./pages/RoomList";
import HotelBookingList from "./pages/list/HotelBookingList";
import Bank from "./pages/master/Bank";
import ContactType from "./pages/master/ContactType";
import MarkupType from "./pages/master/MarkupType";
import Currency from "./pages/master/Currency";
import HotelRegistrationActions from "./pages/HotelRegistrationActions";
import MarketType from "./pages/master/MarketType";
import Region from "./pages/master/Region";
import Province from "./pages/master/Province";
import CityMapping from "./pages/master/CityMapping";
import HotelBookingPage from "./pages/HotelBookingPage";
import AgentReg from "./pages/Registration/AgentReg";
import HotelReg from "./pages/Registration/HotelReg";
import HotelList from "./pages/Registration/HotelList";
import EmployeeReg from "./pages/Registration/EmployeeReg";
import CabProviderReg from "./pages/Registration/CabProviderReg";
import CabRates from "./pages/Registration/CabRates";
import ActivityProviderReg from "./pages/Registration/ActivityProviderReg";
import ActivityRates from "./pages/Registration/ActivityRates";
import PackageReg from "./pages/Registration/PackageReg";
import PackageRates from "./pages/Registration/PackageRates";
import SupplierReg from "./pages/Registration/SupplierReg";
import CompulsoryEventsPage from "./pages/HotelActions/Compulsery/CompulsoryEventsPage";
import OccupancyAndMinimumLength from "./pages/HotelActions/OccupancyAndMinimumLength/OccupancyAndMinimumLength";
import HotelAvailability from "./pages/HotelActions/Availability/HotelAvailability";
import MakeUrOwnPackage from "./pages/search/MakeUrOwnPackage";
import Calendar from "./pages/Calendar";
import HotelCategory from "./pages/master/HotelCategory";
import HotelType from "./pages/master/HotelType";
import OccupancyType from "./pages/master/OccupancyType";
import SeasonType from "./pages/master/SeasonType";
import RoomCategory from "./pages/master/RoomCategory";
import RoomType from "./pages/master/RoomType";
import RoomAmenity from "./pages/master/RoomAmenity";
import HotelAmenity from "./pages/master/HotelAmenity";
import MealPlan from "./pages/master/MealPlan";
import MasterAgentCategory from "./pages/master/MasterAgentCategory";
import PackageCategory from "./pages/master/PackageCategory";
import PackageType from "./pages/master/PackageType";
import DayActivities from "./pages/master/DayActivities";
import ItineraryDetails from "./pages/master/ItineraryDetails";
import VisaDetails from "./pages/master/VisaDetails";
import TermsAndConditions from "./pages/master/TermsAndConditions";
import ValidityPage from "./pages/HotelActions/Validities/ValidityPage";
import IndividualHotelSearch from "./pages/HotelActions/IndividualHotelSearch";
import ContractRate from "./pages/HotelActions/ContractRate/ContractRate";
import Promotion from "./pages/HotelActions/Promotion/Promotion";
import Policy from "./pages/HotelActions/Policy/Policy";
import CreateContractRate from "./pages/HotelActions/ContractRate/CreateContractRate";
import EditContractRate from "./pages/HotelActions/ContractRate/EditContractRate";
import CopyContractRate from "./pages/HotelActions/ContractRate/CopyContractRate";
import OfferZone from "./pages/OfferZone";
import OfferImageUpload from "./pages/OfferImageUpload";
import AgentAccounts from "./pages/inhouseAccounts/AgentAccounts";
import AgentsPaymentHistory from "./pages/inhouseAccounts/AgentsPaymentHistory";
import AgentsAutoGeneratedInvoice from "./pages/inhouseAccounts/AgentsAutoGeneratedInvoice";
import ExtranetHotelDashboard from "./pages/ExtranetHotelDashboard";
import SpecialRates from "./pages/HotelActions/Promotion/SpecialRates";
import EditSpecialRates from "./pages/HotelActions/Promotion/EditSpecialRates";
import DiscountPromotion from "./pages/HotelActions/Promotion/DiscountPromotion";
import EditDiscountPromotion from "./pages/HotelActions/Promotion/EditDiscountPromotion";
import StayPayPromotion from "./pages/HotelActions/Promotion/StayPayPromotion";
import EditStayPayPromotion from "./pages/HotelActions/Promotion/EditStayPayPromotion";






export default function App() {
  return (
    <div>
      <Routes>
        <Route path="/" element={<Login />} />
        <Route path="/select-userRole" element={<SelectRole />} />
        <Route path="/register" element={<Register />} />
        <Route path="/agentDashboard" element={<AgentDashboard />} />
        {/* Protected Routes */}
       <Route
          path="/hotels"
          element={
            <PrivateRoute>
              <>
                <Hotels />
              </>
            </PrivateRoute>
          }
        />
        <Route
          path="/adminDashboard"
          element={
            <PrivateRoute>
              <AdminDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/agentDashboard"
          element={
            <PrivateRoute>
              <AgentDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/booking-details/hotel-booking-list"
          element={
            <PrivateRoute>
              <HotelBookingList />
            </PrivateRoute>
          }
        />
        <Route
          path="/staffDashboard"
          element={
            <PrivateRoute>
              <StaffDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/extranetDashboard"
          element={
            <PrivateRoute>
              <ExtranetHotelDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/landingPage"
          element={
            <PrivateRoute>
              <LandingPage />
            </PrivateRoute>
          }
        />
        <Route
          path="/test"
          element={
            <PrivateRoute>
              <Test />
            </PrivateRoute>
          }
        />

        {/* Masters */}
        <Route path="/masters/designations" element={<Designations />} />
        <Route path="/masters/bank" element={<Bank />} />
         <Route path="/masters/contact-type" element={<ContactType />} />
         <Route path="/masters/markup-type" element={<MarkupType />} />
         <Route path="/masters/currency" element={<Currency />} />
        <Route path="/new-booking/hotel" element={<HotelSearch />} />
        <Route path="/new-booking/make-your-own-package" element={<MakeUrOwnPackage />} />
        <Route path="/room-list" element={<RoomList />} />
        <Route path="/masters/market-type" element={<MarketType />} />
        <Route path="/masters/region" element={<Region />} />
        <Route path="/masters/countries" element={<Country />} />
        <Route path="/masters/states" element={<Province />} />
       <Route path="/masters/destination" element={<Destination />} />
       <Route path="/masters/city-mapping" element={<CityMapping />} />
       <Route path="/masters/hotel-category" element={<HotelCategory />} />
       <Route path="/masters/hotel-type" element={<HotelType />} />
       <Route path="/masters/occupancy-type" element={<OccupancyType />} />
       <Route path="/masters/season-type" element={<SeasonType />} />
       <Route path="/masters/room-category" element={<RoomCategory />} />
       <Route path="/masters/room-types" element={<RoomType />} />
       <Route path="/masters/hotel-amenity" element={<HotelAmenity />} />
       <Route path="/masters/room-amenity" element={<RoomAmenity />} />
       <Route path="/masters/meal-plans" element={<MealPlan />} />
       <Route path="/masters/agent-category" element={<MasterAgentCategory />} />
       <Route path="/masters/package-category" element={<PackageCategory />} />
       <Route path="/masters/package-type" element={<PackageType />} />
       <Route path="/masters/day-activity" element={<DayActivities />} />
       <Route path="/masters/itinerary-details" element={<ItineraryDetails />} />
       <Route path="/masters/visa-information" element={<VisaDetails />} />
       <Route path="/masters/terms-and-conditions" element={<TermsAndConditions />} />
     
       

       {/* Registration */}
       <Route path="/hotel-booking-page" element={<HotelBookingPage/>} />
       <Route path="/registration/agent" element={<AgentReg />} />
       <Route path="/registration/employee" element={<EmployeeReg />} />
       <Route path="/registration/cabProvider" element={<CabProviderReg />} />
       <Route path="/cab-rates" element={<CabRates />} />
       <Route path="/registration/activityProvider" element={<ActivityProviderReg />} />
       <Route path="activity-rates" element={<ActivityRates />} />
       <Route path="/registration/package" element={<PackageReg />} />
       <Route path="/package-rates" element={<PackageRates />} />
       <Route path="/registration/supplier" element={<SupplierReg />} />
       <Route path="/registration/hotel" element={<HotelList />} />
       <Route path="/registration/hotel/create" element={<HotelReg />} />
       <Route path="/registration/hotel/create/:id" element={<HotelReg />} />


       {/* Hotel Actions */}

       <Route path="/hotel-details/:id" element={<HotelRegistrationActions />} />
       {/* compulsory events */}
      <Route path="/registration/hotel/:id/compulsory-events" element={<CompulsoryEventsPage />} />
      <Route path="/hotel-actions/:id/occupancy-and-minimumlength" element={<OccupancyAndMinimumLength />} />
      {/* hotelavailability */}
      <Route path="/hotel-actions/:id/hotel-availability" element={<HotelAvailability />} />
      <Route path="/hotel-actions/:id/validity-period-details" element={<ValidityPage />} />
      {/* selected hotelsearch from booking page */}
      <Route path="/hotel-actions/:id/individual-hotel-search" element={<IndividualHotelSearch />} />
      {/* contract rate */}
      <Route path="/hotel-actions/:id/contract-rate" element={<ContractRate />} />
      <Route path="/hotel-actions/hotel/:id/contract-rate/create" element={<CreateContractRate />} />
      <Route path="/hotel-actions/hotel/:id/contract-rate/:contractRateId/edit" element={<EditContractRate />} />
      <Route path="/hotel-actions/hotel/:id/contract-rate/:editId/copy" element={<CopyContractRate />} />
      {/* promotion */}
      <Route path="/hotel-actions/:id/promotions" element={<Promotion />} />
      <Route path="/hotel-actions/:id/promotion/special-rate/save" element={<SpecialRates />} />
      <Route path="/hotel-actions/:id/promotion/special-rate/edit/:editId" element={<EditSpecialRates />} />
      <Route path="/hotel-actions/:id/promotion/staypay/save" element={<StayPayPromotion />} />
      <Route path="/hotel-actions/:id/promotion/staypay/edit/:editId" element={<EditStayPayPromotion />} />
      <Route path="/hotel-actions/:id/promotion/discount/save" element={<DiscountPromotion />} />
      <Route path="/hotel-actions/:id/promotion/discount/edit/:editId" element={<EditDiscountPromotion />} />
      {/* policy */}
      <Route path="/hotel-actions/:id/hotel-policy" element={<Policy />} />
      
      
      {/* inhouse accounts    */}
      <Route path="/inhouse-accounts/agent" element={<AgentAccounts />} />
      <Route path="/inhouse-accounts/agent-payment-history/:id" element={<AgentsPaymentHistory />} />
      <Route path="/inhouse-accounts/agent-auto-generated-invoice/:id" element={<AgentsAutoGeneratedInvoice />} />

       {/* sidebarMenus    */}
      <Route path="/calendar" element={<Calendar />} />
      <Route path="/offer" element={<OfferZone />} />
      <Route path="/upload-offer-image" element={<OfferImageUpload />} />

      </Routes>

      {/* Toast container */}
      <Toaster
        // position="top-center"
        containerStyle={{
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
        }}
        toastOptions={{
          duration: 5000,
          style: {
            background: "#363636",
            color: "#fff",
          },
          success: {
            duration: 5000,
            iconTheme: {
              primary: "#4bb543",
              secondary: "#fff",
            },
          },
          error: {
            duration: 6000,
            iconTheme: {
              primary: "#ff3333",
              secondary: "#fff",
            },
          },
        }}
      />
    </div>
  );
}
