import React from "react";
import { Routes, Route, Link } from "react-router-dom";
import Login from "./pages/Login";
import SelectRole from "./pages/SelectRole";
import Register from "./pages/Register";

import Country from "./pages/master/Country";
import Destination from "./pages/master/Destination";
import Hotels from "./pages/master/Hotels";
import PrivateRoute from "./components/PrivateRoute";
import AgentDashboard from "./pages/AgentDashboard";
import AdminDashboard from "./pages/AdminDashboard";
import StaffDashboard from "./pages/StaffDashboard";
import Test from "./pages/Test";
import LandingPage from "./pages/LandingPage";
import { Toaster } from "react-hot-toast";
import Designations from "./pages/master/Designation";
import HotelSearch from "./pages/HotelSearch";
import RoomList from "./pages/RoomList";
import HotelBookingList from "./pages/list/HotelBookingList";
import CustomBookingList from "./pages/list/CustomBookingList";
import Bank from "./pages/master/Bank";
import ContactType from "./pages/master/ContactType";
import MarkupType from "./pages/master/MarkupType";
import Currency from "./pages/master/Currency";
import HotelRegistrationActions from "./pages/HotelRegistrationActions";
import MarketType from "./pages/master/MarketType";
import Region from "./pages/master/Region";
import Province from "./pages/master/Province";
import CityMapping from "./pages/master/CityMapping";

import AgentReg from "./pages/Registration/AgentReg";
import HotelReg from "./pages/Registration/HotelReg";
import HotelList from "./pages/Registration/HotelList";
import EmployeeReg from "./pages/Registration/EmployeeReg";
import CabProviderReg from "./pages/Registration/CabProviderReg";
import CabRates from "./pages/Registration/CabRates";
import ActivityProviderReg from "./pages/Registration/ActivityProviderReg";
import ActivityRates from "./pages/Registration/ActivityRates";
import PackageReg from "./pages/Registration/PackageReg";
import PackageRates from "./pages/Registration/PackageRates";
import SupplierReg from "./pages/Registration/SupplierReg";
import CompulsoryEventsPage from "./pages/HotelActions/Compulsery/CompulsoryEventsPage";
import OccupancyAndMinimumLength from "./pages/HotelActions/OccupancyAndMinimumLength/OccupancyAndMinimumLength";
import HotelAvailability from "./pages/HotelActions/Availability/HotelAvailability";
import MakeUrOwnPackage from "./pages/search/MakeUrOwnPackage";
import Calendar from "./pages/Calendar";
import HotelCategory from "./pages/master/HotelCategory";
import HotelType from "./pages/master/HotelType";
import OccupancyType from "./pages/master/OccupancyType";
import SeasonType from "./pages/master/SeasonType";
import RoomCategory from "./pages/master/RoomCategory";
import RoomType from "./pages/master/RoomType";
import RoomAmenity from "./pages/master/RoomAmenity";
import HotelAmenity from "./pages/master/HotelAmenity";
import MealPlan from "./pages/master/MealPlan";
import MasterAgentCategory from "./pages/master/MasterAgentCategory";
import PackageCategory from "./pages/master/PackageCategory";
import PackageType from "./pages/master/PackageType";
import DayActivities from "./pages/master/DayActivities";
import ItineraryDetails from "./pages/master/ItineraryDetails";
import VisaDetails from "./pages/master/VisaDetails";
import TermsAndConditions from "./pages/master/TermsAndConditions";
import ValidityPage from "./pages/HotelActions/Validities/ValidityPage";
import IndividualHotelSearch from "./pages/HotelActions/IndividualHotelSearch";
import ContractRate from "./pages/HotelActions/ContractRate/ContractRate";
import Promotion from "./pages/HotelActions/Promotion/Promotion";
import Policy from "./pages/HotelActions/Policy/Policy";
import CreateContractRate from "./pages/HotelActions/ContractRate/CreateContractRate";
import EditContractRate from "./pages/HotelActions/ContractRate/EditContractRate";
import CopyContractRate from "./pages/HotelActions/ContractRate/CopyContractRate";
import OfferZone from "./pages/OfferZone";
import OfferImageUpload from "./pages/OfferImageUpload";
import AgentAccounts from "./pages/inhouseAccounts/AgentAccounts";
import AgentsPaymentHistory from "./pages/inhouseAccounts/AgentsPaymentHistory";
import AgentsAutoGeneratedInvoice from "./pages/inhouseAccounts/AgentsAutoGeneratedInvoice";
import ExtranetHotelDashboard from "./pages/ExtranetHotelDashboard";
import SpecialRates from "./pages/HotelActions/Promotion/SpecialRates";
import EditSpecialRates from "./pages/HotelActions/Promotion/EditSpecialRates";
import DiscountPromotion from "./pages/HotelActions/Promotion/DiscountPromotion";
import EditDiscountPromotion from "./pages/HotelActions/Promotion/EditDiscountPromotion";
import StayPayPromotion from "./pages/HotelActions/Promotion/StayPayPromotion";
import EditStayPayPromotion from "./pages/HotelActions/Promotion/EditStayPayPromotion";
import PolicyUpdate from "./pages/HotelActions/Policy/PolicyUpdate";
import PolicyCreate from "./pages/HotelActions/Policy/PolicyCreate";
import CompanyProfile from "./pages/CompanyProfile";
import Profile from "./pages/Profile/Profile";
import ChangePassword from "./pages/Profile/ChangePassword";
import Logout from "./pages/Profile/Logout";
import MakePkgCombineSearch from "./pages/search/MakePkgCombineSearch";
import AccomodationRoomList from "./pages/roomlist/makeyourownpkg/AccomodationRoomList";
import Invoice from "./pages/Invoice";
import MakePkgBookingPage from "./pages/roomlist/makeyourownpkg/MakePkgBookingPage";
import GenerateQuotationBooking from "./pages/roomlist/makeyourownpkg/GenerateQuotationBooking";
import QuotationBookingList from "./pages/roomlist/makeyourownpkg/QuotationBookingList";
import QuotationBookingPage from "./pages/roomlist/makeyourownpkg/QuotationBookingPage";

// :bar_chart: Reports
import ReportBooking from "./pages/report/BookingReport";
import CancellationReport from "./pages/report/CancellationReport";
import InventoryStatus from "./pages/report/InventoryStatus";
import HotelWise from "./pages/report/HotelWise";
import Accounts from "./pages/report/Accounts";
import DayWise from "./pages/report/DayWise";
import MonthlyWise from "./pages/report/MonthlyWise";
import Comparison from "./pages/report/Comparison";
import AgentWise from "./pages/report/AgentWise";
import ContractExpiryReport from "./pages/report/ContractExpiryReport";
import Contractrate from "./pages/report/Contractrate";
import UserReport from "./pages/report/UserReport";
import Stopsalereport from "./pages/report/Stopsalereport";
import UserLogins from "./pages/report/UserLogins";
import OfflineBookingDailySalesStatement from "./pages/report/OfflineBookingDailySalesStatement";
import OnlineDailySalesReport from "./pages/report/OnlineDailySalesReport";
import TimeLimitOnlineDailySalesReport from "./pages/report/TimeLimitOnlineDailySalesReport";
import ExternalApiRoomList from "./pages/ExternalApiRoomList";
import HotelBookingPage from "./pages/booking/HotelBookingPage";
import ApiBookingPageForHotels from "./pages/booking/ApiBookingPageForHotels";
import { CabSearch } from "./pages/search/cab/CabSearch";
import CabBookingPage from "./pages/booking/CabBookingPage";
import ActivitySearch from "./pages/search/activity/ActivitySearch";
import ActivityBookingPage from "./pages/booking/ActivityBookingPage";
import CabBookingList from "./pages/list/CabBookingList";
import ActivityBookingList from "./pages/list/ActivityBookingList";
import HotelMapping from "./pages/master/HotelMapping";


export default function App() {
  return (
    <div>
      <Routes>
        {/* Public Routes */}
        <Route path="/" element={<Login />} />
        <Route path="/login" element={<Login />} />
        <Route path="/select-userRole" element={<SelectRole />} />
        <Route path="/register" element={<Register />} />
        
       
     {/* Protected Routes */}
<Route
  path="/adminDashboard"
  element={
    <PrivateRoute>
      <AdminDashboard />
    </PrivateRoute>
  }
/>

        <Route
          path="/agentDashboard"
          element={
            <PrivateRoute>
              <AgentDashboard />
            </PrivateRoute>
          }
        />
       
        <Route
          path="/staffDashboard"
          element={
            <PrivateRoute>
              <StaffDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/extranetDashboard"
          element={
            <PrivateRoute>
              <ExtranetHotelDashboard />
            </PrivateRoute>
          }
        />
        <Route
          path="/landingPage"
          element={
            <PrivateRoute>
              <LandingPage />
            </PrivateRoute>
          }
        />

        {/* Topbar profile  */}
        <Route path="/view-profile" element={<PrivateRoute><Profile /> </PrivateRoute> }/>
        <Route path="/change-password" element={<PrivateRoute><ChangePassword /> </PrivateRoute> }/>
        <Route path="/log-out" element={<PrivateRoute><Logout /> </PrivateRoute> }/>

        {/* Masters */}
        <Route path="/masters/designations" element={<PrivateRoute><Designations /></PrivateRoute>} />
        <Route path="/masters/bank" element={<PrivateRoute><Bank /></PrivateRoute>} />
        <Route path="/masters/contact-type" element={<PrivateRoute><ContactType /></PrivateRoute>} />
        <Route path="/masters/markup-type" element={<PrivateRoute><MarkupType /></PrivateRoute>} />
        <Route path="/masters/currency" element={<PrivateRoute><Currency /></PrivateRoute>} />
        <Route path="/masters/market-type" element={<PrivateRoute><MarketType /></PrivateRoute>} />
        <Route path="/masters/region" element={<PrivateRoute><Region /></PrivateRoute>} />
        <Route path="/masters/countries" element={<PrivateRoute><Country /></PrivateRoute>} />
        <Route path="/masters/states" element={<PrivateRoute><Province /></PrivateRoute>} />
        <Route path="/masters/destination" element={<PrivateRoute><Destination /></PrivateRoute>} />
        <Route path="/masters/city-mapping" element={<PrivateRoute><CityMapping /></PrivateRoute>} />
        <Route path="/masters/hotel-category" element={<PrivateRoute><HotelCategory /></PrivateRoute>} />
        <Route path="/masters/hotel-type" element={<PrivateRoute><HotelType /></PrivateRoute>} />
        <Route path="/masters/occupancy-type" element={<PrivateRoute><OccupancyType /></PrivateRoute>} />
        <Route path="/masters/season-type" element={<PrivateRoute><SeasonType /></PrivateRoute>} />
        <Route path="/masters/room-category" element={<PrivateRoute><RoomCategory /></PrivateRoute>} />
        <Route path="/masters/room-types" element={<PrivateRoute><RoomType /></PrivateRoute>} />
        <Route path="/masters/hotel-amenity" element={<PrivateRoute><HotelAmenity /></PrivateRoute>} />
        <Route path="/masters/room-amenity" element={<PrivateRoute><RoomAmenity /></PrivateRoute>} />
        <Route path="/masters/meal-plans" element={<PrivateRoute><MealPlan /></PrivateRoute>} />
        <Route path="/masters/agent-category" element={<PrivateRoute><MasterAgentCategory /></PrivateRoute>} />
        <Route path="/masters/package-category" element={<PrivateRoute><PackageCategory /></PrivateRoute>} />
        <Route path="/masters/package-type" element={<PrivateRoute><PackageType /></PrivateRoute>} />
        <Route path="/masters/day-activity" element={<PrivateRoute><DayActivities /></PrivateRoute>} />
        <Route path="/masters/itinerary-details" element={<PrivateRoute><ItineraryDetails /></PrivateRoute>} />
        <Route path="/masters/visa-information" element={<PrivateRoute><VisaDetails /></PrivateRoute>} />
        <Route path="/masters/terms-and-conditions" element={<PrivateRoute><TermsAndConditions /></PrivateRoute>} />
        <Route path="/masters/hotel-mapping" element={<PrivateRoute><HotelMapping /></PrivateRoute>} />
     
        {/* :bar_chart: Reports */}
        <Route path="/report/booking" element={<ReportBooking />} />
        <Route path="/report/cancellation" element={<CancellationReport />} />
        <Route path="/report/inventory-status" element={<InventoryStatus />} />
        <Route path="/report/hotel-wise" element={<HotelWise />} />
        <Route path="/report/accounts" element={<Accounts />} />
        <Route path="/report/day-wise" element={<DayWise />} />
        <Route path="/report/monthly-wise" element={<MonthlyWise />} />
        <Route path="/report/comparison" element={<Comparison />} />
        <Route path="/report/agent-wise" element={<AgentWise />} />
        <Route path="/report/contract-expiry" element={<ContractExpiryReport />} />
        <Route path="/report/contract-rate" element={<Contractrate />} />
        <Route path="/report/user-report" element={<UserReport />} />
        <Route path="/report/stop-sale" element={<Stopsalereport />} />
        <Route path="/report/user-logins" element={<UserLogins />} />
        <Route path="/report/offline-daily-sales" element={<OfflineBookingDailySalesStatement />} />
        <Route path="/report/online-daily-sales" element={<OnlineDailySalesReport />} />
        <Route path="/report/time-limit-daily-sales" element={<TimeLimitOnlineDailySalesReport />} />

       {/* New Booking */}
        <Route path="/new-booking/hotel" element={<PrivateRoute><HotelSearch /></PrivateRoute>} />
        <Route path="/hotel-booking-page" element={<PrivateRoute><HotelBookingPage /></PrivateRoute>} />
        <Route path="/api-booking-page-hotels" element={<PrivateRoute><ApiBookingPageForHotels /></PrivateRoute>} />
        <Route path="/new-booking/make-your-own-package" element={<PrivateRoute><MakeUrOwnPackage /></PrivateRoute>} />
        <Route path="/new-booking/make-your-own-package/booking-page" element={<PrivateRoute><MakePkgBookingPage /></PrivateRoute>} />
        <Route path="/room-list" element={<PrivateRoute><RoomList /></PrivateRoute>} />
        <Route path="/api-room-list" element={<PrivateRoute><ExternalApiRoomList /></PrivateRoute>} />
        <Route path="/new-booking/make-your-own-package/search" element={<PrivateRoute><MakePkgCombineSearch /></PrivateRoute>} />
        <Route path="/booking-details/hotel-booking-list" element={<PrivateRoute><HotelBookingList /> </PrivateRoute>}/>
        <Route path="/booking-details/custom-booking-list" element={<PrivateRoute><CustomBookingList /> </PrivateRoute>}/>
        <Route path="/make-your-pkg-room-list" element={<PrivateRoute><AccomodationRoomList /> </PrivateRoute>}/>
        <Route path="/make-your-own-package/generate-quotation-booking" element={<PrivateRoute><GenerateQuotationBooking /> </PrivateRoute>}/>
        <Route path="/make-your-own-package/confirm-quotation-bookingpage" element={<PrivateRoute><QuotationBookingPage /> </PrivateRoute>}/>
        <Route path="/booking-details/quotation-booking-list" element={<PrivateRoute><QuotationBookingList /> </PrivateRoute>}/>
        <Route path="/new-booking/cab" element={<PrivateRoute><CabSearch /> </PrivateRoute>}/>
        <Route path="/cab-booking-page" element={<PrivateRoute><CabBookingPage /> </PrivateRoute>}/>
        <Route path="/new-booking/tours-and-activities" element={<PrivateRoute><ActivitySearch /> </PrivateRoute>}/>
        <Route path="/new-booking/tours-and-activities/booking" element={<PrivateRoute><ActivityBookingPage /> </PrivateRoute>}/>

        {/* Booking List/Details */}
        <Route path="/booking-details/cab-booking-list" element={<PrivateRoute><CabBookingList /></PrivateRoute>} />
        <Route path="/booking-details/activity-booking-list" element={<PrivateRoute><ActivityBookingList /></PrivateRoute>} />

        {/* Company Profile */}
        <Route path="/company-profile" element={<PrivateRoute><CompanyProfile /></PrivateRoute>} />

        {/* Registration */}
        <Route path="/registration/agent" element={<PrivateRoute><AgentReg /></PrivateRoute>} />
        <Route path="/registration/employee" element={<PrivateRoute><EmployeeReg /></PrivateRoute>} />
        <Route path="/registration/cabProvider" element={<PrivateRoute><CabProviderReg /></PrivateRoute>} />
        <Route path="/cab-rates" element={<PrivateRoute><CabRates /></PrivateRoute>} />
        <Route path="/registration/activityProvider" element={<PrivateRoute><ActivityProviderReg /></PrivateRoute>} />
        <Route path="/activity-rates" element={<PrivateRoute><ActivityRates /></PrivateRoute>} />
        <Route path="/registration/package" element={<PrivateRoute><PackageReg /></PrivateRoute>} />
        <Route path="/package-rates" element={<PrivateRoute><PackageRates /></PrivateRoute>} />
        <Route path="/registration/supplier" element={<PrivateRoute><SupplierReg /></PrivateRoute>} />
        <Route path="/registration/hotel" element={<PrivateRoute><HotelList /></PrivateRoute>} />
        <Route path="/registration/hotel/create" element={<PrivateRoute><HotelReg /></PrivateRoute>} />
        <Route path="/registration/hotel/create/:id" element={<PrivateRoute><HotelReg /></PrivateRoute>} />


        {/* Hotel Actions */}
        <Route path="/hotel-details/:id" element={<PrivateRoute><HotelRegistrationActions /></PrivateRoute>} />
        {/* compulsory events */}
        <Route path="/registration/hotel/:id/compulsory-events" element={<PrivateRoute><CompulsoryEventsPage /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/occupancy-and-minimumlength" element={<PrivateRoute><OccupancyAndMinimumLength /></PrivateRoute>} />
        {/* hotelavailability */}
        <Route path="/hotel-actions/:id/hotel-availability" element={<PrivateRoute><HotelAvailability /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/validity-period-details" element={<PrivateRoute><ValidityPage /></PrivateRoute>} />
        {/* selected hotelsearch from booking page */}
        <Route path="/hotel-actions/:id/individual-hotel-search" element={<PrivateRoute><IndividualHotelSearch /></PrivateRoute>} />
        {/* contract rate */}
        <Route path="/hotel-actions/:id/contract-rate" element={<PrivateRoute><ContractRate /></PrivateRoute>} />
        <Route path="/hotel-actions/hotel/:id/contract-rate/create" element={<PrivateRoute><CreateContractRate /></PrivateRoute>} />
        <Route path="/hotel-actions/hotel/:id/contract-rate/:contractRateId/edit" element={<PrivateRoute><EditContractRate /></PrivateRoute>} />
        <Route path="/hotel-actions/hotel/:id/contract-rate/:editId/copy" element={<PrivateRoute><CopyContractRate /></PrivateRoute>} />
        {/* promotion */}
        <Route path="/hotel-actions/:id/promotions" element={<PrivateRoute><Promotion /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/special-rate/save" element={<PrivateRoute><SpecialRates /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/special-rate/edit/:editId" element={<PrivateRoute><EditSpecialRates /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/staypay/save" element={<PrivateRoute><StayPayPromotion /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/staypay/edit/:editId" element={<PrivateRoute><EditStayPayPromotion /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/discount/save" element={<PrivateRoute><DiscountPromotion /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/promotion/discount/edit/:editId" element={<PrivateRoute><EditDiscountPromotion /></PrivateRoute>} />
        {/* policy */}
        <Route path="/hotel-actions/:id/hotel-policy" element={<PrivateRoute><Policy /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/hotel-policy/create" element={<PrivateRoute><PolicyCreate /></PrivateRoute>} />
        <Route path="/hotel-actions/:id/hotel-policy/:editId/edit" element={<PrivateRoute><PolicyUpdate /></PrivateRoute>} />
      
        {/* inhouse accounts */}
        <Route path="/inhouse-accounts/agent" element={<PrivateRoute><AgentAccounts /></PrivateRoute>} />
        <Route path="/inhouse-accounts/agent-payment-history/:id" element={<PrivateRoute><AgentsPaymentHistory /></PrivateRoute>} />
        <Route path="/inhouse-accounts/agent-auto-generated-invoice/:id" element={<PrivateRoute><AgentsAutoGeneratedInvoice /></PrivateRoute>} />

        {/* sidebarMenus */}
        <Route path="/calendar" element={<PrivateRoute><Calendar /></PrivateRoute>} />
        <Route path="/invoice" element={<PrivateRoute><Invoice /></PrivateRoute>} />
        <Route path="/offer" element={<PrivateRoute><OfferZone /></PrivateRoute>} />
        <Route path="/upload-offer-image" element={<PrivateRoute><OfferImageUpload /></PrivateRoute>} />

      </Routes>

      {/* Toast container */}
      <Toaster
        // position="top-center"
        containerStyle={{
          top: "50%",
          left: "50%",
          transform: "translate(-50%, -50%)",
        }}
        toastOptions={{
          duration: 5000,
          style: {
            background: "#363636",
            color: "#fff",
          },
          success: {
            duration: 5000,
            iconTheme: {
              primary: "#4bb543",
              secondary: "#fff",
            },
          },
          error: {
            duration: 6000,
            iconTheme: {
              primary: "#ff3333",
              secondary: "#fff",
            },
          },
        }}
      />
    </div>
  );
}
